import Theme from '@/components/Common/Theme'
import Footer from '@/components/Footer/Footer'
import Navbar from '@/components/Navbar/Navbar'
import StoreProvider from '@/store/StoreProvider'
import { Inter } from 'next/font/google'
import StyledComponentsRegistry from './lib/registry'
import { AntdRegistry } from '@ant-design/nextjs-registry';
import '@/styles/app.scss';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'DSC-WeDemo',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <AntdRegistry>
        <StyledComponentsRegistry>
          <html lang="en">
            <body className={inter.className}>
              <Navbar />
              {children}
              <Footer />
            </body>
          </html>
        </StyledComponentsRegistry>
      </AntdRegistry>
    </StoreProvider>
  )
}
